name: Update Pre-commit Hooks Versions

on:
  schedule:
    - cron: "51 5 * * 1" # Every Monday morning
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Python set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Python cache set up
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-py-cache

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit autoupdate
        run: |
          pre-commit autoupdate

      - name: Commit changes if any
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"
            git commit -am "Update .pre-commit-config.yaml"
            git push
          fi
